# Generated by Django 5.2.6 on 2025-10-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('new', 'New Arrivals'), ('best', 'Best Sellers')], default='new', max_length=20),
        ),
    ]
